from __future__ import annotations

from datetime import datetime

from lab.database.crud.product_review import (
    add_product_review,
    delete_product_review,
    get_all_reviews,
    get_review_by_id,
    replace_product_review_full,
    update_product_review_partial,
)
from lab.database.models.product_review import ProductReview, UpdateProductReview
from lab.utils.console.logger import Badge, Logger


def main():
    # 1. 添加第一个评论
    Logger.custom("--- 流程开始：添加第一个评论 ---", badge=Badge("START", fore="black", back="cyan"))
    review1_data = ProductReview(
        name="Abdulazeez",
        product="TestDriven TDD Course",
        rating=4.9,
        review="Excellent course!",
        # date will be automatically generated by default_factory
    )
    add_result1 = add_product_review(review_data=review1_data)
    if add_result1:
        Logger.info(f"添加评论成功: {add_result1.get('message')}")
    else:
        Logger.error("添加评论失败。停止执行后续操作。")
        exit()

    # 2. 获取所有评论以找到新添加的评论的 ID
    Logger.custom("\n--- 流程：获取所有评论以找到最新ID ---", badge=Badge("GET_ALL", fore="black", back="cyan"))
    all_reviews = get_all_reviews()
    first_review_id = None
    if all_reviews:
        # 假设最新添加的评论是列表中的最后一个 (通常情况)
        first_review_id = all_reviews[-1].get("id")
        Logger.info(f"最新添加评论的 ID 为: {first_review_id}")
    else:
        Logger.error("无法获取任何评论，或获取评论失败。停止执行后续操作。")
        exit()

    if not first_review_id:
        Logger.error("无法获取到最新评论的 ID，后续操作将无法执行。停止执行。")
        exit()

    # 3. 根据 ID 获取单个评论
    Logger.custom(
        f"\n--- 流程：根据 ID 获取评论 ({first_review_id}) ---", badge=Badge("GET_ONE", fore="black", back="cyan")
    )
    get_review_by_id(first_review_id)

    # 4. 局部更新评论 (PATCH)
    Logger.custom(f"\n--- 流程：局部更新评论 ({first_review_id}) ---", badge=Badge("PATCH", fore="black", back="cyan"))
    update_partial_data = UpdateProductReview(name="张三", rating=5.0)
    updated_review = update_product_review_partial(review_id=first_review_id, updates=update_partial_data)
    if updated_review:
        Logger.info(f"评论局部更新成功: {updated_review}")
    else:
        Logger.error("局部更新评论失败。")

    # 再次获取以确认更新
    Logger.custom(
        f"\n--- 流程：再次获取以确认局部更新 ({first_review_id}) ---", badge=Badge("CONFIRM", fore="black", back="cyan")
    )
    get_review_by_id(first_review_id)

    # 5. 添加第二个评论 (用于 PUT 操作的示例)
    Logger.custom("\n--- 流程：添加第二个评论 (为PUT准备) ---", badge=Badge("ADD_2", fore="black", back="cyan"))
    review2_data = ProductReview(name="李四", product="Web 开发进阶", rating=5.0, review="完美，学到了很多新东西！")
    add_result2 = add_product_review(review_data=review2_data)
    second_review_id = None
    if add_result2:
        Logger.info(f"添加第二个评论成功: {add_result2.get('message')}")
        # 获取所有评论以找到新添加的评论的 ID
        all_reviews_after_second_add = get_all_reviews()
        if all_reviews_after_second_add:
            # 假设最新的评论是列表中的最后一个
            second_review_id = all_reviews_after_second_add[-1].get("id")
            Logger.info(f"第二个评论的 ID 为: {second_review_id}")
    else:
        Logger.error("添加第二个评论失败。")

    if second_review_id:
        # 6. 完全替换第二个评论 (PUT)
        Logger.custom(
            f"\n--- 流程：完全替换第二个评论 ({second_review_id}) ---", badge=Badge("PUT", fore="black", back="cyan")
        )
        replace_full_data = ProductReview(
            name="张三",  # PUT 使用此ID的数据
            product="你好",
            rating=4.9,
            review="Excellent course! Updated review.",
            date=datetime.now(),  # Pydantic will handle this to ISO format string
        )
        replaced_review = replace_product_review_full(review_id=second_review_id, new_data=replace_full_data)
        if replaced_review:
            Logger.info(f"评论完全替换成功: {replaced_review}")
        else:
            Logger.error("完全替换评论失败。")

        # 再次获取以确认替换
        Logger.custom(
            f"\n--- 流程：再次获取以确认完全替换 ({second_review_id}) ---",
            badge=Badge("CONFIRM", fore="black", back="cyan"),
        )
        get_review_by_id(second_review_id)
    else:
        Logger.error("无法获取到第二个评论的 ID，无法执行完全替换操作。")

    # 7. 删除第一个评论
    Logger.custom(
        f"\n--- 流程：删除第一个评论 ({first_review_id}) ---", badge=Badge("DELETE", fore="black", back="red")
    )
    delete_result = delete_product_review(first_review_id)
    if delete_result:
        Logger.info(f"删除评论成功: {delete_result.get('message')}")
    else:
        Logger.error("删除评论失败。")

    # 8. 再次获取所有评论，确认删除
    Logger.custom("\n--- 流程：再次获取所有评论，确认删除 ---", badge=Badge("VERIFY", fore="black", back="cyan"))
    get_all_reviews()

    Logger.custom("\n--- 流程结束 ---", badge=Badge("END", fore="black", back="yellow"))
