openai_base_url = ""
openai_api_key = ""
openai_model = ""
deeplx_api_key = ""
system_prompt_name = "elaina"
speaker_lang = "ZH"
speaker_model = "gpt_sovits"
faster_first_response = true
segment_method = "pysbd"
interrupt_method = "user"
