[asr]
FFMPEG_PATH = "ffmpeg"
device = "cuda"
custom_output_dir = false
cache_dir = "./cache"
output_dir = "./output"
asr_model_provider = "whisper"
cut = false
cut_line = 400
combine = false
combine_line = 400
max_sentence_length = 20

[asr.funasr]
batch_size_s = 300
punctuation_list = "，。；、？！,.;?!"
hot_words_path = "./hot_words.txt"
base_model = "./models/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch"
vad_model = "./models/speech_fsmn_vad_zh-cn-16k-common-pytorch"
punc_model = "./models/punc_ct-transformer_zh-cn-common-vocab272727-pytorch"
sense_voice_model = "./models/SenseVoiceSmall"
need_punc = false

[asr.whisper]
whisper_models_base_dir = "./models/whisper/"
whisper_model_size = "turbo"

[webui]
guide = "open"
subtitle_speed = "normal"

[agent]
enable_mcp = true
character_name = "elaina"
deeplx_api_key = ""
user_lang = "ZH"
speaker_lang = "EN"
speaker_model = "gpt_sovits"
faster_first_response = false
segment_method = "pysbd"
interrupt_method = "user"

[agent.chat_model]
llm_provider = "oaipro"
llm_model_name = "gpt-5.1-2025-11-13"
support_vision = false

[agent.tool_model]
llm_provider = "cerebras"
llm_model_name = "qwen-3-235b-a22b-instruct-2507"

[agent.vision_model]
llm_provider = "oaipro"
llm_model_name = "gpt-5.1-2025-11-13"

[agent.llm.openai]
llm_api_key = ""
llm_base_url = "https://api.openai.com/v1"
api_format = "chat_completion"

[agent.llm.lingyi]
llm_api_key = ""
llm_base_url = "https://api.lingyiwanwu.com/v1"
api_format = "chat_completion"

[agent.llm.gemini]
llm_api_key = ""
llm_base_url = "https://generativelanguage.googleapis.com/v1beta/openai/"
api_format = "chat_completion"

[agent.llm.oaipro]
llm_api_key = ""
llm_base_url = "https://api.oaipro.com/v1"
api_format = "chat_completion"

[agent.llm.cerebras]
llm_api_key = ""
llm_base_url = "https://api.cerebras.ai/v1"
api_format = "chat_completion"

[mcp.servers.timeemi]
transport = "http"
enable = true
host = "127.0.0.1"
port = 4200
path = "/"
log_level = "debug"

[mcp.servers.vision]
transport = "http"
enable = true
host = "127.0.0.1"
port = 4201
path = "/"
log_level = "debug"

[mcp.servers.tool]
transport = "http"
enable = true
host = "127.0.0.1"
port = 4202
path = "/"
log_level = "debug"

[mcp.tools]
user_agent = "XnneHangLab-MCP/1.1"

[mcp.tools.web_search]
provider = "duckduckgo"
timeout_s = 10.0
searxng_url = "http://127.0.0.1:8000"

[mcp.tools.web_fetch]
respect_robots = true
robots_fail_closed = false
use_jina_fallback = false
jina_api_key = ""
timeout_s = 10.0
max_chars_default = 8000

[mcp.tool_context]
tool_budget_tokens = 2200
recent_n_msgs = 10
include_prev_assistant = true
pinned_max_chars = 2400
reserve_tokens = 350
min_window_tokens = 200

[package]
funasr = false
whisper = false
to_do_list = true
yutto_uiya = true
gpt_sovits = true

[root]
root_dir = "D:\\tmp\\XnneHangLab"
