conf_version = "v1.5.1"

[asr]
FFMPEG_PATH = "ffmpeg"
device = "cpu"
custom_output_dir = false
cache_dir = "./cache"
output_dir = "./output"
asr_model_provider = "qwen"
punctuation_list = "，。；、？！,.;?!"
cut = false
cut_line = 400
combine = false
combine_line = 400
max_sentence_length = 20

[asr.sherpa]
asr_model_dir = "./models/sherpa-onnx-paraformer-zh-2023-09-14"
vad_model_path = "./models/silero_vad.onnx"
num_threads = 2

[asr.qwen_asr]
model_dir = "./models"
preload_models = [
    "0.6b",
]
model_0_6b_path = "./models/Qwen3-ASR-0.6B"
model_1_7b_path = "./models/Qwen3-ASR-1.7B"
forced_aligner_path = "./models/Qwen3-ForcedAligner-0.6B"
device = "cpu"

[webui]
guide = "open"
subtitle_speed = "normal"

[agent]
enable_tool = true
deeplx_api_key = ""
user_lang = "ZH"
speaker_lang = "EN"
speaker_model = "gpt_sovits"
faster_first_response = false
max_vision_concurrency = 4
require_detailed = true
segment_method = "pysbd"
interrupt_method = "user"
memory_agent_profile = "profiles/elaina.toml"
memory_chat_profile = "profiles/congyin.toml"

[agent.chat_model]
llm_provider = "oaipro"
llm_model_name = "gpt-5.1-2025-11-13"
support_vision = false

[agent.vision_model]
llm_provider = "oaipro"
llm_model_name = "gpt-5.1-2025-11-13"

[agent.embedding]
api_key = ""
base_url = "https://api.oaipro.com/v1"
model = "text-embedding-3-small"

[agent.prompts]
live2d_expression_prompt = "./prompts/live2d_expression_prompt.txt"
think_tag_prompt = "./prompts/think_tag_prompt.txt"
character_prompt = "./prompts/characters/elaina.txt"
vision_prompt = "./prompts/vision_prompt.txt"
tool_prompt = "./prompts/tool_prompt.txt"

[agent.llm.openai]
llm_api_key = ""
llm_base_url = "https://api.openai.com/v1"
api_format = "chat_completion"

[agent.llm.lingyi]
llm_api_key = ""
llm_base_url = "https://api.lingyiwanwu.com/v1"
api_format = "chat_completion"

[agent.llm.gemini]
llm_api_key = ""
llm_base_url = "https://generativelanguage.googleapis.com/v1beta/openai/"
api_format = "chat_completion"

[agent.llm.oaipro]
llm_api_key = ""
llm_base_url = "https://api.oaipro.com/v1"
api_format = "chat_completion"

[agent.llm.cerebras]
llm_api_key = ""
llm_base_url = "https://api.cerebras.ai/v1"
api_format = "chat_completion"

[package]
sherpa_asr = false
qwen_asr = false
to_do_list = true
yutto_uiya = true
gpt_sovits = true
qwen_tts = false
memory_bench = false

[root]
root_dir = ""

[server]
host = "localhost"
port = 12393
config_alts_dir = "characters"
uvicorn_log_level = "warning"

[vtuber.character_config]
conf_name = "elaina-local"
conf_uid = "elaina-local-001"
live2d_model_name = "Elaina"
character_name = "Elaina"
avatar = "ico_lss.png"
human_name = "Human"

[vtuber.character_config.tts_preprocessor_config]
remove_special_char = true
ignore_brackets = true
ignore_parentheses = true
ignore_asterisks = true
ignore_angle_brackets = true

[memory_bench]
search_limit = 10
server_api_key = ""
