# ===========================
# 这是中文版本的配置文件。
# 一些配置项被调整成了适合中文用户的预设配置，方便无脑开玩。
# 如果你希望使用英文版本，请用 config_templates/conf.default.yaml 的内容替换本文件。 # TODO 很好的做法，不使用像我那样的 dict 的做法，而是以两个 config 作为管理和切换中英文
# ===========================

# 系统设置：与服务器初始化相关的设置
system_config:
  conf_version: 'v1.1.1' # 配置文件版本
  host: 'localhost' # 服务器监听的地址，'0.0.0.0' 表示监听所有网络接口；如果需要安全，可以使用 '127.0.0.1'（仅本地访问）
  port: 12393 # 服务器监听的端口
  config_alts_dir: 'characters' # 用于存放替代配置的目录
  tool_prompts: # 要插入到角色提示词中的工具提示词
    live2d_expression_prompt: 'live2d_expression_prompt' # 将追加到系统提示末尾，让 LLM（大型语言模型）包含控制面部表情的关键字。支持的关键字将自动加载到 `[<insert_emomap_keys>]` 的位置。
    # 启用 think_tag_prompt 可让不具备思考输出的 LLM 也能展示内心想法、心理活动和动作（以括号形式呈现），但不会进行语音合成。更多详情请参考 think_tag_prompt。
    # think_tag_prompt: 'think_tag_prompt'
  # group_conversation_prompt: 'group_conversation_prompt' # 当使用群聊时，此提示词将添加到每个 AI 参与者的记忆中。

# 默认角色的配置
character_config:
  conf_name: 'elaina-local' # 角色配置文件的名称
  conf_uid: 'elaina-local-001' # 角色配置的唯一标识符
  live2d_model_name: 'Elaina' # Live2D 模型名称
  character_name: 'Elaina' # 将在群聊中使用，并显示为 AI 的名称。
  avatar: 'ico_lss.png' # 建议使用正方形图像作为头像。将其保存到 avatars 文件夹中。留空则使用角色名称的首字母作为头像。
  human_name: 'Human' # 将在群聊中使用，并显示为人类的名称。


  #  =================== LLM 后端设置 ===================
  tts_preprocessor_config:
    # 关于进入 TTS 的文本预处理的设置

    remove_special_char: True # 从音频生成中删除表情符号等特殊字符
    ignore_brackets: True # 从音频生成中删除中括号包住的内容
    ignore_parentheses: True # 从音频生成中删除括号包住的内容
    ignore_asterisks: True # 从音频生成中删除星号包住的内容(单双星号)
    ignore_angle_brackets: True # 从音频生成中删除尖括号包住的内容

