services:
  neo4j:
    image: neo4j:5
    container_name: membench-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4jneo4j
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
